### ISSUE TITLE
issues in running python bulid_models.py

### ISSUE THREAD

**Issue by analystanand** [Nayyaroddeen/spam_classification#1]
I have extracted dataset inside raw_input

`Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/PycharmProjects/spam_classification/bulid_models.py", line 235, in <module>
    count_vec=count_vector_model(count_vec)
  File "/home/PycharmProjects/spam_classification/bulid_models.py", line 17, in count_vector_model
    train_counts = count_vect.fit_transform(list_of_docs)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 869, in fit_transform
    self.fixed_vocabulary_)
  File "/home/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 811, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words`

**Comment by Nayyaroddeen** [comment]
Please keep .ham.txt and .spam.txt files from the enron1's  spam/ and ham/  sdirectories into raw_input.

Example:
raw_input/ folder should contain  .spam.txt and .ham.txt files

**Comment by analystanand** [comment]
I have tried both mode.. once with folders and once with directly pouring .txt file into raw_text

**Comment by Nayyaroddeen** [comment]
Please check that folder name should be raw_input not raw_text

**Comment by analystanand** [comment]
![image](https://user-images.githubusercontent.com/18388960/40667820-ab9254c2-6380-11e8-9add-b53525159de3.png)

**Comment by Nayyaroddeen** [comment]
pushed the input files too please check and confirm. Thanks

**Comment by analystanand** [comment]
![image](https://user-images.githubusercontent.com/18388960/40671245-f96bcd60-6388-11e8-93ed-cd72ea537a42.png)
